#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill for Token Pilot setup.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail



if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    
WRITTEN_SECRET=() 
SKIPPED=()        


_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}


ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}


ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}


write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}


set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

TOTAL_STAGES=8

banner "Token Pilot Environment Setup"

stage "Database: Supabase Connection"
say "Token Pilot logs telemetry and cost savings to PostgreSQL via Drizzle ORM."
open_url "https://supabase.com/dashboard"
step "Open or create your Supabase project."
step "Go to Project Settings -> Database -> Connection string."
step "Select URI mode (or Transaction pooler mode on port 6543) and copy the URL."
step "Ensure [YOUR-PASSWORD] is replaced with your real database password."
ask_secret DATABASE_URL "Paste your DATABASE_URL:"
if [[ -n "$DATABASE_URL" ]]; then
  write_env DATABASE_URL "$DATABASE_URL"
fi

stage "Groq API: Low-Cost / Free Tier"
say "Groq powers fast, low-cost execution for simple prompt queries (e.g. Llama 3.3)."
open_url "https://console.groq.com/keys"
step "In Groq Console, click 'Create API Key'."
step "Name the key 'token-pilot' and copy the secret key (starts with gsk_)."
ask_secret GROQ_API_KEY "Paste your Groq API key:"
if [[ -n "$GROQ_API_KEY" ]]; then
  write_env GROQ_API_KEY "$GROQ_API_KEY"
fi

stage "Google AI Studio: Medium Complexity Tier"
say "Google Gemini Flash handles medium-complexity queries at low cost."
open_url "https://aistudio.google.com/app/apikey"
step "Click 'Create API key' and choose or create a Google Cloud project."
step "Copy the generated API key."
ask_secret GOOGLE_API_KEY "Paste your Google AI Studio API key:"
if [[ -n "$GOOGLE_API_KEY" ]]; then
  write_env GOOGLE_API_KEY "$GOOGLE_API_KEY"
fi

stage "OpenAI: Frontier High Complexity Tier"
say "OpenAI GPT-4o is reserved for multi-step reasoning and frontier tasks."
open_url "https://platform.openai.com/api-keys"
step "Click 'Create new secret key', name it 'token-pilot', and copy the key (starts with sk-)."
ask_secret OPENAI_API_KEY "Paste your OpenAI API key:"
if [[ -n "$OPENAI_API_KEY" ]]; then
  write_env OPENAI_API_KEY "$OPENAI_API_KEY"
fi

stage "Anthropic: Complex Reasoning Tier"
say "Anthropic Claude Opus / Sonnet powers alternative high-complexity routing."
open_url "https://console.anthropic.com/settings/keys"
step "Click 'Create Key', name it 'token-pilot', and copy the secret key (starts with sk-ant-)."
ask_secret ANTHROPIC_API_KEY "Paste your Anthropic API key:"
if [[ -n "$ANTHROPIC_API_KEY" ]]; then
  write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
fi

stage "DeepSeek: Alternative Provider (Optional)"
say "DeepSeek provides high-performance reasoning at low cost (press Enter to skip if not using)."
open_url "https://platform.deepseek.com/api_keys"
step "Click 'Create API key' if you have a DeepSeek account, or press Enter to skip."
ask_secret DEEPSEEK_API_KEY "Paste your DeepSeek API key (or press Enter to skip):"
if [[ -n "$DEEPSEEK_API_KEY" ]]; then
  write_env DEEPSEEK_API_KEY "$DEEPSEEK_API_KEY"
fi

stage "Gateway Security & Server Defaults"
say "Token Pilot authenticates incoming API requests using a master API_KEY."
GEN_KEY=""
if command -v openssl >/dev/null 2>&1; then
  GEN_KEY=$(openssl rand -base64 24 2>/dev/null || true)
elif command -v node >/dev/null 2>&1; then
  GEN_KEY=$(node -e "console.log(require('crypto').randomBytes(24).toString('base64'))" 2>/dev/null || true)
fi
if [[ -z "$GEN_KEY" ]]; then
  GEN_KEY="tp_secret_$(date +%s)"
fi

EXISTING_KEY=$(_existing "API_KEY" || true)
if [[ -z "$EXISTING_KEY" ]]; then
  say "Suggested auto-generated key: $GEN_KEY"
  ask API_KEY "Paste custom API_KEY (or press Enter to use suggested key):"
  if [[ -z "$API_KEY" ]]; then
    API_KEY="$GEN_KEY"
  fi
else
  ask API_KEY "Enter Gateway Master API_KEY:"
fi
write_env API_KEY "$API_KEY"

if [[ -z "$(_existing 'PORT' || true)" ]]; then
  write_env PORT "3000"
fi
if [[ -z "$(_existing 'NODE_ENV' || true)" ]]; then
  write_env NODE_ENV "development"
fi
if [[ -z "$(_existing 'CORS_ORIGIN' || true)" ]]; then
  write_env CORS_ORIGIN "*"
fi
if [[ -z "$(_existing 'RATE_LIMIT_MAX' || true)" ]]; then
  write_env RATE_LIMIT_MAX "10"
fi
if [[ -z "$(_existing 'RATE_LIMIT_WINDOW_MS' || true)" ]]; then
  write_env RATE_LIMIT_WINDOW_MS "3600000"
fi

stage "Database Schema Initialization"
say "Token Pilot uses Drizzle Kit to create database tables (request_logs, etc.)."
if confirm "Run 'npm run db:push' now to sync database schema?"; then
  say "Running Drizzle schema push..."
  if npm run db:push; then
    say "Database tables successfully synchronized."
  else
    warn "Drizzle push failed. Verify DATABASE_URL in .env and run 'npm run db:push' manually."
  fi
  pause "Press Enter to continue"
else
  note "Skipping schema sync. You can run 'npm run db:push' at any time."
  pause "Press Enter to continue"
fi

finish
